SYS_DRM = '/sys/class/drm'
SYS_VIDEO4LINUX = '/sys/class/video4linux'
RUN_USER_PREFIX = '/run/user'
VAR_RUN_DBUS = '/var/run/dbus/system_bus_socket'
SYSFS_BLUETOOTH = '/sys/class/bluetooth'
FALLBACK_SOUND = '/usr/share/sounds/freedesktop/stereo/message.oga'

WP_SYSTEM_CONF_DIR = '/etc/wireplumber/wireplumber.conf.d'
WP_USER_CONF_SUBDIR = '.config/wireplumber/wireplumber.conf.d'
WP_STATE_DIR = '.local/state/wireplumber'

CMD_WPCTL = 'wpctl'
CMD_PW_DUMP = 'pw-dump'
CMD_PW_CLI = 'pw-cli'
CMD_PW_PLAY = 'pw-play'
CMD_V4L2_CTL = 'v4l2-ctl'
CMD_XRANDR = 'xrandr'
CMD_MODETEST = 'modetest'
CMD_BLUETOOTHCTL = 'bluetoothctl'
CMD_HCICONFIG = 'hciconfig'
CMD_HCITOOL = 'hcitool'
CMD_LSUSB = 'lsusb'
CMD_SYSTEMCTL = 'systemctl'
CMD_SPEAKER_TEST = 'speaker-test'

SOUNDS_DIR = '/usr/share/sounds/alsa'
